# -*- coding: utf-8 -*-
"""WhisperTranscribe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NQH4KphD6Pj42nkY4mtjrEtJXr18n6DL
"""

# Remove or comment out the following lines:
# !pip -qqq install git+https://github.com/openai/whisper.git
# !pip -qqq install pytube
# !pip install pytubefix

from OpenAI import Whisper
import torch
import os
from pytubefix import YouTube

device = "cuda" if torch.cuda.is_available() else "cpu"

#Load model
whisper_model = whisper.load_model("large",device=device)

def video_to_audio(video_URL, destination, final_filename):
  # Get the video
  yt = YouTube(video_URL)

  # Convert video to Audio
  audio = yt.streams.filter(only_audio=True).first()

  # Save to destination
  output = audio.download(output_path = destination)

  _, ext = os.path.splitext(output)
  new_file = final_filename + '.mp3'

  # Change the name of the file
  os.rename(output, os.path.join(destination, new_file))

# Video to audio
video_URL = 'https://www.youtube.com/watch?v=E9lAeMz1DaM'
destination = "."
final_filename = "motivational_speech"
video_to_audio(video_URL, destination, final_filename)

audio_file = "motivational_speech.mp3"
try:
    result = whisper_model.transcribe(audio_file)
    print(result["text"])
except Exception as e:
    print(f"Error transcribing audio: {e}")
